version: "3.4"

services:
  neo4j:
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7687:7687
  webapp:
    build:
      context: webapp
      target: production
  backend:
    build:
      context: backend
      target: production
    ports:
      - 4001:4001 # remove as soon we refactored all backend factories

